config/routes.rb
JeffFit::Application.routes.draw do
  resources :exercises, :programs, :exercise_programs

  root 'pages#home'

  get '/home', to: 'pages#home'

  resources :users, except: [:new]

  get '/register', to: 'users#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'


end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates :exercise_name, presence: true,
                    length: { minimum: 1 }
  has_many :exercise_programs
  has_many :programs, through: :exercise_programs
end

app/models/exercise_program.rb
class ExerciseProgram < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :program
end

app/models/program.rb
class Program < ActiveRecord::Base
  validates :program_name, presence: true, length: { minimum: 1, maximum: 25 }
  has_many :exercise_programs, dependent: :destroy
  has_many :exercises, through: :exercise_programs
  belongs_to :user
  validates :user_id, presence: true
  serialize :day_of_week, Array


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :programs
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 2, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end


end

app/controllers/exercise_programs_controller.rb
class ExerciseProgramsController < ApplicationController

end

app/controllers/exercises_controller.rb
	class ExercisesController < ApplicationController
		before_action :set_exercise, only: [:edit, :update, :show]


	def new
		@exercise = Exercise.new
	end

	def create
  	@exercise = Exercise.new(exercise_params)

		respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'exercise was successfully created.' }
        format.json
      else
        format.html { render action: 'new' }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
	end

	def index
  	@exercises = Exercise.all
	end

	def edit
	end

	def update
  	if @exercise.update(exercise_params)
    	redirect_to @exercise
  	else
    	render 'edit'
  	end
	end

	def destroy
  	@exercise = Exercise.find(params[:id])
  	@exercise.destroy

  	redirect_to exercises_path
	end

	private
  		def exercise_params
    		params.require(:exercise).permit(:exercise_name, :description)
  		end

			def set_exercise
				@exercise = Exercise.find(params[:id])
			end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You are logged in"
      redirect_to programs_path
    else
      flash.now[:danger] = "Your email address or password does not match"
      render 'new'

    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to programs_path if logged_in?
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:edit, :update, :show]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update, :show]



  def new
    @program = Program.new
  end

  def create
  	@program = Program.new(program_params)
    @program.user = current_user

		respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'program was successfully created.' }
        format.json
      else
        format.html { render action: 'new' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
	end

	def index
  	@programs = current_user.programs
	end

	def edit
	end

	def update
  	if @program.update(program_params)
    	redirect_to program_path(@program)
  	else
    	render 'edit'
  	end
	end

	def destroy
  	@program = Program.find(params[:id])
  	@program.destroy

  	redirect_to programs_path
	end

	private
		def program_params
  		params.require(:program).permit(:program_name, :description, day_of_week: [], exercise_ids: [])
		end

    def set_program
      @program = Program.find(params[:id])
    end

    def require_same_user
      if current_user != @program.user
        #TODO: if add admins, need to add !current_user.admin? conditional also
        flash[:danger] = "You can only view and edit your own programs"
        redirect_to programs_path
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account has been created successfully"
      session[:user_id] = @user.id
      redirect_to programs_path
    else
      render 'new'
    end
  end

  def edit

  end


  def update
    if @user.update(user_params)
      flash[:success] = "Your profile has been updated successfully" #TODO why flash message not showing?
      redirect_to programs_path #TODO change to show user page
    else
      render 'edit'
    end
  end

  def show
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user
        flash[:danger] = "You can only edit your own profile"
        redirect_to root_path
      end
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
  def show_sets(exercise, program)
    get_exercise_program_for_exercise(exercise, program).first.number_of_sets
  end

  def show_reps(exercise, program)
    get_exercise_program_for_exercise(exercise, program).first.number_of_reps
  end

  def get_exercise_program_for_exercise(exercise, program)
    exercise.exercise_programs.select { |ex| ex.program_id == program.id }
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/exercises/_form.html.erb
<%= form_for @exercise do |f| %>
  <div id="error_explanation"></div>
  <% if @exercise.errors.any? %>
    <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited
      this exercise from being saved:</h2>
    <ul>
    <% @exercise.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  <% end %>
  <p>
    <%= f.label :exercise_name %><br>
    <%= f.text_field :exercise_name %>

  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit(class: "button") %>
  </p>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing an exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercise_path %>

app/views/exercises/index.html.erb
<h1 id="list_of_exercises_header">List of Exercises</h1>
<%= link_to 'New Exercise', new_exercise_path %>

<table>
  <tr>
    <th id="exercise_name_header">Exercise name</th>
    <th id="exercise_description_header">Description</th>
    <th colspan="3"></th>
  </tr>

  <% @exercises.each do |exercise| %>
    <tr>
      <td id='<%= exercise.exercise_name %>'><%= exercise.exercise_name %></td>
      <td id='<%= exercise.exercise_name %>_description'><%= exercise.description %></td>
      <td><%= link_to 'Show', exercise_path(exercise) %></td>
      <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
      <td><%= link_to 'Delete', exercise_path(exercise), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>Create a new exercise here</h1>

<%= render 'form' %>

app/views/exercises/show.html.erb
<p>
  <strong>Exercise name:</strong>
  <%= @exercise.exercise_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exercise.description %>
</p>

<%= link_to 'Create another new exercise', new_exercise_path %>
<%= link_to 'Exercise List', exercises_path %>
<%= link_to 'Edit', edit_exercise_path(@exercise) %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Jeff-Fit 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <% if logged_in? %>
    <div id="home_button">
      <%= link_to "Home", root_path, type: "button", class: "btn btn-default navbar-btn" %>
    </div>
      <div class="nav-item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
            Exercises <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <li><%= link_to "All Exercies", exercises_path %></li>
            <li><%= link_to "New Exercise", new_exercise_path %></li>
          </ul>
        </li>
      </div>
      <div class="nav-item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
            Programs <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <li><%= link_to "My Programs", programs_path %></li>
            <li><%= link_to "New Program", new_program_path %></li>
          </ul>
        </li>
      </div>
    <% end %>
    <% if logged_in? %>
      <div class="nav-item" id="logout">
        <%= link_to "Logout", logout_path, class: "btn btn-default btn-danger" %>
      </div>
      <ul class="nav-item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.name %> <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <li><%= link_to "View Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JeffFit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>

    <%= render 'layouts/footer' %>

  </div>
</body>
</html>

app/views/logins/new.html.erb
<h1>Login</h1>

<div class="row">
  <div class="well col-md-6 col-md-offset-3">
    <%= form_tag '/login' do %>

      <%= label_tag :email %>
      <%= text_field_tag :email %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= submit_tag 'Login', class: 'btn btn-success' %>


    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Jeff-Fit!</h1>

  <%= link_to "Sign up now!", "", class: "btn btn-lg btn-success" %>

  <%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      Placeholder text to determine what goes here.
    </h3>
    <h2 class="left">Some other placeholder text</h2>
    <p><%= link_to "Placeholder", "", class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Placeholder text to determine what goes here.
    </h3>
    <h2 class="left">Some other placeholder text</h2>
    <p><%= link_to "Placeholder", "", class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Placeholder text to determine what goes here.
    </h3>
    <h2 class="left">Some other placeholder text</h2>
    <p><%= link_to "Placeholder", "", class: "btn btn-warning btn-small" %></p>
  </div>
</div>

app/views/programs/_form.html.erb
  <%= form_for @program do |f| %>
  <div id="error_explanation"></div>
  <% if @program.errors.any? %>
    <h2><%= pluralize(@program.errors.count, "error") %> prohibited
      this program from being saved:</h2>
    <ul>
    <% @program.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>

  <% end %>
  <p>
    <%= f.label :program_name %><br>
    <%= f.text_field :program_name %>

  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <strong>Add exercises to this program:</strong>
    <%= f.collection_check_boxes :exercise_ids, Exercise.all, :id, :exercise_name %>
  </p>


    <%= f.label :day_of_week %>
      <% Date::DAYNAMES.each do |day| %>
        <%= f.check_box :day_of_week, {:multiple => true}, day, nil %>
        <%= day %>
      <% end %>

  <div>
    <%= f.submit(class: "update-program-button") %>
  </div>

<% end %>

app/views/programs/edit.html.erb
<h1>Edit a program</h1>

<%= render 'form' %>

app/views/programs/index.html.erb
<h1 id="list_of_programs_header">List of programs</h1>
<%= link_to 'New Program', new_program_path %>

<table>
  <tr>
    <th id="program_name_header">Program name</th>
    <th id="program_description_header">Description</th>
    <th colspan="3"></th>
  </tr>

  <% @programs.each do |program| %>
    <tr>
      <td id='<%= program.program_name %>'><%= program.program_name %></td>
      <td id='<%= program.program_name %>_description'><%= program.description %></td>
      <td><%= link_to 'Show', program_path(program) %></td>
      <td><%= link_to 'Edit', edit_program_path(program) %></td>
      <td><%= link_to 'Delete', program_path(program), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', new_program_path %>

app/views/programs/new.html.erb
<h1>Create a new program here</h1>

<%= render 'form' %>

app/views/programs/show.html.erb
<%= link_to 'Program List', programs_path %>
<%= link_to 'Edit', edit_program_path(@program) %>

<p>
  <strong>Program name:</strong>
  <%= @program.program_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

<p>
  <strong>Exercises:</strong>
  <% if @program.exercises.any? %>

    <% @program.exercises.each do |exercise| %>
      <%= exercise.exercise_name %>
      <%= "The number of sets for this exercise is #{show_sets(exercise, @program)}" %>
      <%= "The number of reps for this exercise is #{show_reps(exercise, @program)}" %>
    <% end %>
  <% else %>
    <%= "No Exercises Selected for this Program" %>
  <% end %>
</p>

<p>
  <strong>Days of the Week:</strong>
  <% if @program.day_of_week.any? %>
    <% @program.day_of_week.each do |dow| %>
      <%= dow %>
    <% end %>
  <% else %>
    <%= "No Days Selected for this Program" %>
  <% end %>
</p>

app/views/users/_form.html.erb
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit(@user.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>

     <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Register your account</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User page for <%= @user.name %></h1>

app/views/welcome/index.html.erb
<h1>Welcome to Jeff-Fit!</h1>

<%= link_to 'Exercises', controller: 'exercises' %>

<%= link_to 'Create new exercise', new_exercise_path %>

<%= link_to 'Programs', controller: 'programs' %>

<%= link_to 'Create new program', new_program_path %>